---
# 🟢 PARTIE EXTRACT

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [3]:
import numpy as np
#modules
import pandas as pd
from pandas.core.dtypes import dtypes

In [4]:
# TON CODE ICI
#clients datafile
data_client = pd.read_csv(r"D:\python_projects\sales\clients.csv")
data_produit = pd.read_csv(r"D:\python_projects\sales\produits.csv")
data_q1 = pd.read_csv(r"D:\python_projects\sales\commandes_Q1.csv")
data_q2 = pd.read_csv(r"D:\python_projects\sales\commandes_Q2.csv")

In [5]:
print(data_client.shape)
print(data_client.columns)
print(data_client.dtypes)

(515, 9)
Index(['client_id', 'nom', 'email', 'ville', 'region', 'segment',
       'date_inscription', 'ca_historique', 'actif'],
      dtype='str')
client_id               str
nom                     str
email                   str
ville                   str
region                  str
segment                 str
date_inscription        str
ca_historique       float64
actif                  bool
dtype: object

In [6]:
data_client.head(3)

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

In [7]:
data_q1.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [8]:
# TON CODE ICI
colonnes_q1 = set(data_q1.columns)
colonnes_q2 = set(data_q2.columns)

print(f"Colonnes présentes dans Q2 mais absentes de Q1 :blush: {sorted(colonnes_q2 - colonnes_q1)}")
#print(sorted(colonnes_q2 - colonnes_q1))

print(f"Colonnes présentes dans Q1 mais absentes de Q2 :blush: {sorted(colonnes_q1 - colonnes_q2)}")

Colonnes présentes dans Q2 mais absentes de Q1 :blush: ['devise', 'moyen_paiement']
Colonnes présentes dans Q1 mais absentes de Q2 :blush: ['mode_paiement']

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [9]:
x1 = data_q1.columns
x2 = data_q2.columns

dx = pd.DataFrame(x1, x2)
#dx

Donc, le moyen_paiement et mode_paiement exigent d'harmoniser.

In [10]:
# TON CODE ICI
data_q2 = data_q2.rename(columns={"moyen_payement": "mode_paiement"})
data_q2.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='str')

In [11]:
data_q1["devis"] = "EUR" #currency
data_q1.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devis
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [12]:
print(data_q1.shape)
print(data_q2.shape)

(3020, 11)
(3220, 11)

In [13]:
# TON CODE ICI
#ajoute le colonne
data_q1['source'] = 'Q1_2024'
data_q2['source'] = 'Q2_2024'

data_conc = [data_q1, data_q2]
# Concatenate row-wise and reset index
df_fin = pd.concat(data_conc, axis=0, ignore_index=True, sort=False)
df_fin.shape

(6240, 14)

In [14]:
dff = df_fin['source'].value_counts()
dff

source
Q2_2024    3220
Q1_2024    3020
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [15]:
# TON CODE ICI
def extract(q1_path, q2_path, client_path, produit_path)->dict:
    data_client = pd.read_csv(client_path)
    data_produit = pd.read_csv(produit_path)
    data_q1 = pd.read_csv(q1_path)
    data_q2 = pd.read_csv(q2_path)

    # Harmonize column names
    data_q2 = data_q2.rename(columns={"moyen_payement": "mode_paiement"})
    data_q1["devis"] = "EUR"  # currency

    # Add source column
    data_q1['source'] = 'Q1_2024'
    data_q2['source'] = 'Q2_2024'

    # Concatenate row-wise and reset index
    df_fin = pd.concat([data_q1, data_q2], axis=0, ignore_index=True, sort=False)
    
    return df_fin, data_client, data_produit
extract(r"D:\python_projects\sales\commandes_Q1.csv", r"D:\python_projects\sales\commandes_Q2.csv", r"D:\python_projects\sales\clients.csv", r"D:\python_projects\sales\produits.csv")
df_fin, data_client, data_produit = extract(r"D:\python_projects\sales\commandes_Q1.csv", r"D:\python_projects\sales\commandes_Q2.csv", r"D:\python_projects\sales\clients.csv", r"D:\python_projects\sales\produits.csv")
df_fin.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devis', 'source', 'moyen_paiement', 'devise'],
      dtype='str')

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [16]:
# TON CODE ICI
def audit_dataframe(df, nom="DataFrame"):
    print(f"=== Audit du {nom} ===\n")

    # Shape
    print("Shape :", df.shape, "\n")

    # NaN total
    total_nan = df.isna().sum().sum()
    print(f"Nombre total de NaN : {total_nan}\n")

    # NaN par colonne
    nan_par_col = df.isna().mean() * 100
    print("Pourcentage de NaN par colonne :")
    print(nan_par_col.round(2).astype(str) + " %")
    print()

    # Doublons
    doublons = df.duplicated().sum()
    print(f"Nombre de doublons : {doublons}\n")

    # Types des colonnes
    print("Types des colonnes :")
    print(df.dtypes)
    print("\n=== Fin de l'audit ===")
#Exemple data pour clients
audit_dataframe(data_client, "Dataset Clients")

=== Audit du Dataset Clients ===

Shape : (515, 9)

Nombre total de NaN : 31

Pourcentage de NaN par colonne :
client_id            0.0 %
nom                  0.0 %
email               6.02 %
ville                0.0 %
region               0.0 %
segment              0.0 %
date_inscription     0.0 %
ca_historique        0.0 %
actif                0.0 %
dtype: str

Nombre de doublons : 15

Types des colonnes :
client_id               str
nom                     str
email                   str
ville                   str
region                  str
segment                 str
date_inscription        str
ca_historique       float64
actif                  bool
dtype: object

=== Fin de l'audit ===

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [17]:
# 1. Détecter et afficher le nombre de doublons

def audit_dataframe(df, nom="DataFrame"):
    print(f"Audit du {nom} \n")

    nb_doublons = df.duplicated().sum()
    print(f"Nombre de doublons : {nb_doublons}")

    # 2. Montrer 3 exemples de lignes dupliquées
    print("\nExemples de lignes dupliquées :")
    print(df[df.duplicated()].head(3))

    # 3. supprimer les doublons (garder la première occurrence)
    df_sans_doublons = df.drop_duplicates(keep="first")

    # 4. Vérifier qu'il n'en reste plus
    nb_restants = df_sans_doublons.duplicated().sum()
    print(f"\nDoublons restants après nettoyage : {nb_restants}")
# TON CODE ICI
#Exemple data pour clients
audit_dataframe(data_q1, "Dataset Clients")

Audit du Dataset Clients

Nombre de doublons : 20

Exemples de lignes dupliquées :
       commande_id client_id produit_id  quantite  prix_unitaire  \
3000  CMD-Q1-02950   CLI0271    PRD0124         2          55.52
3001  CMD-Q1-00072   CLI0001    PRD0027         7          45.84
3002  CMD-Q1-00145   CLI0441    PRD0020         9         304.72

      montant_total date_commande    statut mode_paiement region_livraison  \
3000         111.04    2024-02-27   annulée            CB    Île-de-France
3001         320.88    2024-03-20  en_cours            CB    Île-de-France
3002        2742.48    2024-02-19    livrée            CB    Île-de-France

     devis   source
3000   EUR  Q1_2024
3001   EUR  Q1_2024
3002   EUR  Q1_2024

Doublons restants après nettoyage : 0

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [18]:
# TON CODE ICI
def audit_dataframe(df, nom="DataFrame"):
    # 1. Afficher les dtypes avant
    #print("Data set: {df}".format(df=df.head()))
    print("Types avant :\n", df.dtypes, "\n")

    # 2. Convertir date_commande en datetime (formats incohérents gérés)
    df["date_commande"] = pd.to_datetime(df["date_commande"], errors="coerce", dayfirst=True)

    # 3. Extraire les composantes temporelles
    df["annee"] = df["date_commande"].dt.year
    df["mois"] = df["date_commande"].dt.month
    df["trimestre"] = df["date_commande"].dt.quarter
    df["jour_semaine"] = df["date_commande"].dt.day_name()

    # 4. Convertir quantite en numérique
    df["quantite"] = pd.to_numeric(df["quantite"], errors="coerce")

    # 5. Afficher les types APRÈS
    print("Types après :\n", df.dtypes)
audit_dataframe(data_q1, "Dataset commande-Q1 et Q2")

Types avant :
 commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devis                   str
source                  str
dtype: object

Types après :
 commande_id                    str
client_id                      str
produit_id                     str
quantite                     int64
prix_unitaire              float64
montant_total              float64
date_commande       datetime64[us]
statut                         str
mode_paiement                  str
region_livraison               str
devis                          str
source                         str
annee                      float64
mois                       float64
trimestre                  float64
jour_semaine                   str
dtype: object

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_20436\877273766.py:8: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["date_commande"] = pd.to_datetime(df["date_commande"], errors="coerce", dayfirst=True)

### Ex T4 ⭐⭐ — Traiter les NaN
Pour chaque colonne avec des NaN, choisissez et appliquez la stratégie adaptée :
- `montant_total` NaN → recalculer depuis `quantite × prix_unitaire`
- `statut` NaN → valeur par défaut `'inconnu'`
- `date_commande` NaT → supprimer la ligne (donnée critique)

Justifiez chaque choix dans un commentaire.

In [19]:
# TON CODE ICI
def audit_dataframe(df, nom="DataFrame"):
    #Total Missing values before population
    #montant_total NaN recalculer depuis quantite * prix_unitaire

    # NaN total before population
    print(f"Missing values before:, {df["montant_total"].isnull().sum()}\n")

    #populate missing values
    df["montant_total"] = df["quantite"]*df["prix_unitaire"]
    total_nan_after = df["montant_total"].isnull().sum()
    print(f"Missing values after population: {total_nan_after}\n")

    #statut NaN valeur par défault 'inconnu'
    df["statut"] = df["statut"].fillna("inconnu")
    print(df["statut"].isnull().sum())

    #date_commande Nat - supprimer la ligne

    print(f"Statut par défault inconnu: {df["montant_total"].fillna(df["montant_total"]).isnull().sum()}")
audit_dataframe(data_q2, "dataset commande_Q1")

Missing values before:, 61

Missing values after population: 0

0
Statut par défault inconnu: 0

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [34]:
# TON CODE ICI
#Detecter les prix negatifs et supprimer les lignes correspondantes
def detect_negative_prices(df):
    # Detecter les prix négatifs
    negative_prices = df[df['prix_unitaire'] < 0]
    print(f"Nombre de lignes avec prix négatif : {len(negative_prices)}")
    
    # Afficher les lignes avec prix négatif
    print("Exemples de lignes avec prix négatif :")
    print(negative_prices.head(3))
    
    # Supprimer les lignes avec prix négatif
    df_cleaned = df[df['prix_unitaire'] >= 0]
    
    return df_cleaned
detect_negative_prices(data_q1)

Nombre de lignes avec prix négatif : 9
Exemples de lignes avec prix négatif :
       commande_id client_id produit_id  quantite  prix_unitaire  \
348   CMD-Q1-00349   CLI0409    PRD0080         8        -131.51
607   CMD-Q1-00608   CLI0330    PRD0028         2         -59.70
1087  CMD-Q1-01088   CLI0219    PRD0057         7         -85.50

      montant_total date_commande  statut mode_paiement region_livraison  \
348         1052.08    2024-03-27  livrée        Chèque             PACA
607          119.40    2024-03-26  livrée        PayPal             PACA
1087         598.50    2024-02-26  livrée        PayPal             PACA

     devis   source   annee  mois  trimestre jour_semaine
348    EUR  Q1_2024  2024.0   3.0        1.0    Wednesday
607    EUR  Q1_2024  2024.0   3.0        1.0      Tuesday
1087   EUR  Q1_2024  2024.0   2.0        1.0       Monday

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devis,source,annee,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,2024.0,3.0,1.0,Monday
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,2024.0,1.0,1.0,Tuesday
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,1.0,1.0,Monday
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024,2024.0,1.0,1.0,Wednesday
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024,2024.0,3.0,1.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,CMD-Q1-02619,CLI0400,PRD0066,7,181.07,1267.49,2024-03-14,livrée,Virement,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,3.0,1.0,Thursday
3016,CMD-Q1-01687,CLI0071,PRD0097,6,149.62,897.72,NaT,livrée,CB,Auvergne-RA,EUR,Q1_2024,NaN,NaN,NaN,NaN
3017,CMD-Q1-01222,CLI0324,PRD0102,8,23.26,186.08,2024-02-06,livrée,CB,Occitanie,EUR,Q1_2024,2024.0,2.0,1.0,Tuesday
3018,CMD-Q1-02488,CLI0093,PRD0036,3,211.79,635.37,2024-02-18,livrée,CB,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,2.0,1.0,Sunday
3019,CMD-Q1-01522,CLI0275,PRD0024,6,20.71,124.26,2024-02-15,livrée,PayPal,Île-de-France,EUR,Q1_2024,2024.0,2.0,1.0,Thursday

In [35]:
# detecter les quantités null ou négatives et supprimer les lignes correspondantes
def detect_invalid_quantities(df):
    # Detecter les quantités nulles ou négatives
    invalid_quantities = df[df['quantite'] <= 0]
    print(f"Nombre de lignes avec quantités nulles ou négatives : {len(invalid_quantities)}")
    
    # Afficher les lignes avec quantités nulles ou négatives
    print("Exemples de lignes avec quantités nulles ou négatives :")
    print(invalid_quantities.head(3))
    
    # Supprimer les lignes avec quantités nulles ou négatives
    df_cleaned = df[df['quantite'] > 0]
    
    return df_cleaned
detect_invalid_quantities(data_q1)

Nombre de lignes avec quantités nulles ou négatives : 12
Exemples de lignes avec quantités nulles ou négatives :
      commande_id client_id produit_id  quantite  prix_unitaire  \
202  CMD-Q1-00203   CLI0371    PRD0070         0          28.37
366  CMD-Q1-00367   CLI0310    PRD0144         0         212.05
630  CMD-Q1-00631   CLI0117    PRD0043         0         100.34

     montant_total date_commande    statut mode_paiement region_livraison  \
202          28.37    2024-03-28    livrée            CB        Occitanie
366         636.15    2024-01-25  en_cours        PayPal        Occitanie
630         602.04    2024-01-21    livrée            CB    Île-de-France

    devis   source   annee  mois  trimestre jour_semaine
202   EUR  Q1_2024  2024.0   3.0        1.0     Thursday
366   EUR  Q1_2024  2024.0   1.0        1.0     Thursday
630   EUR  Q1_2024  2024.0   1.0        1.0       Sunday

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devis,source,annee,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,2024.0,3.0,1.0,Monday
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,2024.0,1.0,1.0,Tuesday
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,1.0,1.0,Monday
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024,2024.0,1.0,1.0,Wednesday
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024,2024.0,3.0,1.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3015,CMD-Q1-02619,CLI0400,PRD0066,7,181.07,1267.49,2024-03-14,livrée,Virement,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,3.0,1.0,Thursday
3016,CMD-Q1-01687,CLI0071,PRD0097,6,149.62,897.72,NaT,livrée,CB,Auvergne-RA,EUR,Q1_2024,NaN,NaN,NaN,NaN
3017,CMD-Q1-01222,CLI0324,PRD0102,8,23.26,186.08,2024-02-06,livrée,CB,Occitanie,EUR,Q1_2024,2024.0,2.0,1.0,Tuesday
3018,CMD-Q1-02488,CLI0093,PRD0036,3,211.79,635.37,2024-02-18,livrée,CB,Nouvelle-Aquitaine,EUR,Q1_2024,2024.0,2.0,1.0,Sunday
3019,CMD-Q1-01522,CLI0275,PRD0024,6,20.71,124.26,2024-02-15,livrée,PayPal,Île-de-France,EUR,Q1_2024,2024.0,2.0,1.0,Thursday

In [ ]:
#Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
def verify_consistency(df):
    # Calculer le montant total basé sur les colonnes existantes
    df['montant_total_calculé'] = df['quantite'] * df['prix_unitaire']
    
    # Identifier les incohérences
    inconsistent_rows = df[abs(df['montant_total'] - df['montant_total_calculé']) > 1e-10]  # Tolérance pour les erreurs d arrondi
    #Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
    def verify_consistency(df):
        # Calculer le montant total basé sur les colonnes existantes
        df['montant_total_calculé'] = df['quantite'] * df['prix_unitaire']
        
        # Identifier les incohérences
        inconsistent_rows = df[abs(df['montant_total'] - df['montant_total_calculé']) > 1e-10]  # Tolérance pour les erreurs d arrondi
        # alias pour conserver le nom utilisé plus bas
        consistent_rows = inconsistent_rows
        print(f"Nombre de lignes avec incohérence : {len(consistent_rows)}")
        
        # Afficher les lignes avec incohérence
        print("Exemples de lignes avec incohérence :")
        print(consistent_rows.head(3))
        
        # Corriger les incohérences (optionnel)
        # df.loc[consistent_rows.index, 'montant_total'] = df.loc[consistent_rows.index, 'montant_total_calculé']
        
        return df
    
    # Afficher les lignes avec incohérence
    print("Exemples de lignes avec incohérence :")
    print(consistent_rows.head(3))
    
    # Corriger les incohérences (optionnel)
    # df.loc[consistent_rows.index, 'montant_total'] = df.loc[consistent_rows.index, 'montant_total_calculé']
    
    return df

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [21]:
# TON CODE ICI

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [22]:
# TON CODE ICI

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [23]:
# TON CODE ICI

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [24]:
# TON CODE ICI

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [25]:
# TON CODE ICI

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [26]:
# TON CODE ICI

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [27]:
# TON CODE ICI

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

In [28]:
# TON CODE ICI

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [29]:
# TON CODE ICI

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [30]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [31]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [32]:
# TON CODE ICI